### ISSUE TITLE
Gabriel Amorin saves are corrputed

### ISSUE THREAD

**Issue by vdcn1** [gbramorim/darksouls-saves#1]
Can't load gabriel save becasuse it shows not completed data inside the file.

**Comment by gbramorim** [comment]
LGTM!

**Comment by tiagosousac** [comment]
VAMOS botar para proxima sprint

**Comment by gbramorim** [comment]
Este produto vai ficar em BACKLOG

**Comment by calazansjennifer** [comment]
i think that we need to contact some assistance to this project.

**Comment by gbramorim** [comment]
Fechando o problema pois marcus está no azerbaijão.
